version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ctd
    container_name: ctd_app_container
    restart: always
    ports:
      - "8081:8081"
    working_dir: /app

  postgres:
    image: postgres
    container_name: sintia_postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "main"
      PGDATA: "/var/lib/postgresql/data/"

  redis:
    image: redis
    container_name: sintia_redis_container
    restart: always
    ports:
      - "6379:6379"